[package]
name = "backend_rust_scylla"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scylla = "0.7.0"
tokio = { version = "1.12", features = ["full"] }
futures = "0.3.6"
uuid = "1.0"
bigdecimal = "0.3.0"
num-bigint = "0.4.3"
tracing = "0.1.25"
tracing-subscriber = { version = "0.3.14", features = ["env-filter"] }